import { defineField, defineType } from 'sanity'

export const pageEn = defineType({
  name: 'pageEn',
  title: 'Página English',
  type: 'document',
  groups: [
    { name: 'hero', title: 'Portada', default: true },
    { name: 'vida', title: 'Life in Ferrol' },
    { name: 'estancias', title: 'Tipos de estancia' },
    { name: 'practica', title: 'Info práctica' },
    { name: 'voces', title: 'Testimonios' },
    { name: 'aplicar', title: 'Cómo aplicar' },
    { name: 'preguntas', title: 'FAQ' },
    { name: 'cierre', title: 'Cierre' },
  ],
  fields: [
    defineField({
      name: 'heroEyebrow',
      title: 'Etiqueta pequeña',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'heroHeading',
      title: 'Titular',
      description: 'El titular grande de esta página, en inglés. Debe ser una frase completa que termine en punto.',
      type: 'string',
      group: 'hero',
      validation: (Rule) => Rule.required().error('Esta página necesita un titular.'),
    }),
    defineField({
      name: 'heroText',
      title: 'Texto de la portada',
      type: 'text',
      rows: 4,
      group: 'hero',
      validation: (Rule) => Rule.required().error('Esta página necesita un texto introductorio.'),
    }),
    defineField({
      name: 'heroImage',
      title: 'Foto principal',
      type: 'imageWithAlt',
      group: 'hero',
      validation: (Rule) => Rule.required().error('Esta página necesita una foto principal.'),
    }),
    defineField({
      name: 'heroImageCaption',
      title: 'Qué foto va en la portada',
      description:
        'Mientras no haya foto subida, este texto describe qué foto hace falta. Por ejemplo: "editorial photo · volunteer group at the Cantábrico coast".',
      type: 'string',
      group: 'hero',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'heroCtaPrimaryLabel',
      title: 'Texto del botón principal',
      description: 'Por ejemplo: "Apply now".',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'heroCtaPrimaryHref',
      title: 'Destino del botón principal',
      description:
        'A dónde lleva el botón. Puede ser un ancla dentro de esta misma página (ej. "#apply") o una URL completa. Si lo dejas vacío, lleva a "#apply".',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'heroCtaSecondaryLabel',
      title: 'Texto del botón secundario',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'heroCtaSecondaryHref',
      title: 'Destino del botón secundario',
      description:
        'A dónde lleva el botón. Puede ser un ancla dentro de esta misma página (ej. "#stays") o una URL completa. Si lo dejas vacío, lleva a "#stays".',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'lifeInFerrolIntro',
      title: 'Introducción de "Life in Ferrol"',
      type: 'sectionIntro',
      group: 'vida',
    }),
    defineField({
      name: 'lifeInFerrolPhotos',
      title: 'Fotos con leyenda',
      description: 'Normalmente son cuatro: la playa, el casco viejo, la comida y el clima.',
      type: 'array',
      of: [{ type: 'lifeInFerrolPhoto' }],
      group: 'vida',
      validation: (Rule) => Rule.min(4).max(4).error('Debe haber exactamente cuatro fotos.'),
    }),
    defineField({
      name: 'whatYouCanDoIntro',
      title: 'Introducción de "Tipos de estancia"',
      description: 'Los programas en sí se gestionan en su propia sección, no aquí.',
      type: 'sectionIntro',
      group: 'estancias',
    }),
    defineField({
      name: 'practicalInfoGettingHere',
      title: 'Columna "Getting here"',
      type: 'infoColumn',
      group: 'practica',
    }),
    defineField({
      name: 'practicalInfoHousing',
      title: 'Columna "Housing"',
      type: 'infoColumn',
      group: 'practica',
    }),
    defineField({
      name: 'practicalInfoLanguage',
      title: 'Columna "Language"',
      type: 'infoColumn',
      group: 'practica',
    }),
    defineField({
      name: 'voicesIntro',
      title: 'Introducción de "Voices from past volunteers"',
      description: 'Los testimonios en sí se gestionan en su propia sección, no aquí.',
      type: 'sectionIntro',
      group: 'voces',
    }),
    defineField({
      name: 'howToApplyIntro',
      title: 'Introducción de "How to apply"',
      type: 'sectionIntro',
      group: 'aplicar',
    }),
    defineField({
      name: 'howToApplySteps',
      title: 'Los pasos',
      description: 'Normalmente son tres: fill the form, video call, come over.',
      type: 'array',
      of: [{ type: 'processStep' }],
      group: 'aplicar',
      validation: (Rule) => Rule.min(3).max(3).error('Debe haber exactamente tres pasos.'),
    }),
    defineField({
      name: 'faqIntro',
      title: 'Introducción de "FAQ"',
      description: 'Las preguntas en sí se gestionan en su propia sección, no aquí.',
      type: 'sectionIntro',
      group: 'preguntas',
    }),
    defineField({
      name: 'closingHeading',
      title: 'Título del cierre',
      type: 'string',
      group: 'cierre',
    }),
    defineField({
      name: 'closingText',
      title: 'Texto del cierre',
      type: 'text',
      rows: 2,
      group: 'cierre',
    }),
    defineField({
      name: 'closingCtaPrimaryHref',
      title: 'Destino del botón "Start application"',
      description:
        'A dónde lleva el botón. Puede ser un ancla dentro de esta misma página (ej. "#apply") o una URL completa. Si lo dejas vacío, lleva a "#apply".',
      type: 'string',
      group: 'cierre',
    }),
  ],
  preview: {
    select: { title: 'heroHeading', media: 'heroImage' },
    prepare({ title, media }) {
      return { title: title || 'Página English', media }
    },
  },
})
