import { defineField, defineType } from 'sanity'

import { richTextField } from '../fields/richText'

export const pageEn = defineType({
  name: 'pageEn',
  title: 'Página Volunteering',
  type: 'document',
  groups: [
    { name: 'hero', title: 'Portada', default: true },
    { name: 'forOrgs', title: 'Bloque 1 · For organisations' },
    { name: 'estancias', title: 'Bloque 2 · For individuals' },
    { name: 'vida', title: 'Life in Ferrol' },
    { name: 'practica', title: 'Info práctica' },
    { name: 'voces', title: 'Testimonios' },
    { name: 'aplicar', title: 'Cómo aplicar' },
    { name: 'preguntas', title: 'FAQ' },
    { name: 'cierre', title: 'Cierre' },
  ],
  fields: [
    defineField({ name: 'heroEyebrow', title: 'Etiqueta pequeña', type: 'string', group: 'hero' }),
    defineField({
      name: 'heroHeading',
      title: 'Titular',
      description: 'El titular grande de esta página, en inglés. Debe ser una frase completa que termine en punto.',
      type: 'string',
      group: 'hero',
      validation: (Rule) => Rule.required().error('Esta página necesita un titular.'),
    }),
    richTextField({
      name: 'heroText',
      title: 'Texto de la portada',
      group: 'hero',
      validation: (Rule) => Rule.required().min(1).error('Esta página necesita un texto introductorio.'),
    }),
    defineField({
      name: 'heroImage',
      title: 'Foto principal',
      type: 'imageWithAlt',
      group: 'hero',
      validation: (Rule) => Rule.required().error('Esta página necesita una foto principal.'),
    }),
    defineField({
      name: 'heroImageCaption',
      title: 'Qué foto va en la portada',
      description:
        'Mientras no haya foto subida, este texto describe qué foto hace falta. Por ejemplo: "editorial photo · volunteer group at the Cantábrico coast".',
      type: 'string',
      group: 'hero',
      validation: (Rule) => Rule.required(),
    }),
    defineField({ name: 'heroCtaPrimaryLabel', title: 'Texto del botón principal', description: 'Por ejemplo: "Apply now".', type: 'string', group: 'hero' }),
    defineField({
      name: 'heroCtaPrimaryHref',
      title: 'Destino del botón principal',
      description: 'A dónde lleva el botón. Puede ser un ancla dentro de esta misma página (ej. "#apply") o una URL completa. Si lo dejas vacío, lleva a "#apply".',
      type: 'string',
      group: 'hero',
    }),
    defineField({ name: 'heroCtaSecondaryLabel', title: 'Texto del botón secundario', type: 'string', group: 'hero' }),
    defineField({
      name: 'heroCtaSecondaryHref',
      title: 'Destino del botón secundario',
      description: 'A dónde lleva el botón. Puede ser un ancla dentro de esta misma página (ej. "#stays") o una URL completa. Si lo dejas vacío, lleva a "#stays".',
      type: 'string',
      group: 'hero',
    }),

    // --- Bloque 1: for organisations (destacado, arriba) ----------------
    defineField({
      name: 'forOrgsIntro',
      title: 'Introducción del bloque',
      description: 'Etiqueta y título de "For organisations". El lector es un coordinador, no un voluntario individual: tono sobrio y profesional.',
      type: 'sectionIntro',
      group: 'forOrgs',
    }),
    defineField({
      name: 'orgCardVolunteers',
      title: 'Tarjeta · Send us your volunteers',
      description: 'Acogemos voluntarios ESC en Ferrol, de 2 a 12 meses.',
      type: 'orgCard',
      group: 'forOrgs',
    }),
    defineField({
      name: 'orgCardVetInterns',
      title: 'Tarjeta · Send us your VET interns',
      description: 'Acogemos prácticas de FP, con apoyo logístico y de alojamiento.',
      type: 'orgCard',
      group: 'forOrgs',
    }),
    defineField({
      name: 'orgCardHostOurs',
      title: 'Tarjeta · Host ours',
      description: 'Enviamos voluntarios y grupos a proyectos de organizaciones socias.',
      type: 'orgCard',
      group: 'forOrgs',
    }),
    defineField({
      name: 'orgCardPartnerships',
      title: 'Tarjeta · Strategic partnerships',
      description: 'KA2, cooperación a largo plazo, redes.',
      type: 'orgCard',
      group: 'forOrgs',
    }),
    defineField({
      name: 'orgStatsYears',
      title: 'Años de experiencia',
      description: 'Por ejemplo: "12".',
      type: 'string',
      group: 'forOrgs',
    }),
    defineField({
      name: 'orgStatsProjects',
      title: 'Número de proyectos',
      description: 'Por ejemplo: "40+".',
      type: 'string',
      group: 'forOrgs',
    }),
    defineField({
      name: 'orgStatsCountries',
      title: 'Países socios',
      description: 'Por ejemplo: "15".',
      type: 'string',
      group: 'forOrgs',
    }),
    defineField({
      name: 'orgStatsOid',
      title: 'OID',
      type: 'string',
      group: 'forOrgs',
    }),
    defineField({
      name: 'orgStatsPic',
      title: 'PIC',
      type: 'string',
      group: 'forOrgs',
    }),
    defineField({
      name: 'orgProfilePdf',
      title: 'Organisation profile (PDF)',
      description: 'El archivo PDF que se descarga con el botón "Download organisation profile". Mientras esté vacío, el botón no se muestra.',
      type: 'file',
      options: { accept: '.pdf' },
      group: 'forOrgs',
    }),

    // --- Bloque 2: for individuals (reutiliza el patrón de mobilityProgram, route "en") ---
    defineField({
      name: 'whatYouCanDoIntro',
      title: 'Introducción del bloque "For individuals"',
      description: 'Los dos caminos individuales (Volunteer in Galicia / Do your mobility with us) se gestionan como Programas de movilidad con ruta "English", no aquí.',
      type: 'sectionIntro',
      group: 'estancias',
    }),

    defineField({ name: 'lifeInFerrolIntro', title: 'Introducción de "Life in Ferrol"', type: 'sectionIntro', group: 'vida' }),
    defineField({
      name: 'lifeInFerrolPhotos',
      title: 'Fotos con leyenda',
      description: 'Normalmente son cuatro: la playa, el casco viejo, la comida y el clima.',
      type: 'array',
      of: [{ type: 'lifeInFerrolPhoto' }],
      group: 'vida',
      validation: (Rule) => Rule.min(4).max(4).error('Debe haber exactamente cuatro fotos.'),
    }),
    defineField({ name: 'practicalInfoGettingHere', title: 'Columna "Getting here"', type: 'infoColumn', group: 'practica' }),
    defineField({ name: 'practicalInfoHousing', title: 'Columna "Housing"', type: 'infoColumn', group: 'practica' }),
    defineField({ name: 'practicalInfoLanguage', title: 'Columna "Language"', type: 'infoColumn', group: 'practica' }),
    defineField({
      name: 'voicesIntro',
      title: 'Introducción de "Voices from past volunteers"',
      description: 'Los testimonios en sí se gestionan en su propia sección, no aquí.',
      type: 'sectionIntro',
      group: 'voces',
    }),
    defineField({ name: 'howToApplyIntro', title: 'Introducción de "How to apply"', type: 'sectionIntro', group: 'aplicar' }),
    defineField({
      name: 'howToApplySteps',
      title: 'Los pasos',
      description: 'Normalmente son tres: fill the form, video call, come over.',
      type: 'array',
      of: [{ type: 'processStep' }],
      group: 'aplicar',
      validation: (Rule) => Rule.min(3).max(3).error('Debe haber exactamente tres pasos.'),
    }),
    defineField({
      name: 'faqIntro',
      title: 'Introducción de "FAQ"',
      description: 'Las preguntas en sí se gestionan en su propia sección, no aquí.',
      type: 'sectionIntro',
      group: 'preguntas',
    }),
    defineField({ name: 'closingHeading', title: 'Título del cierre', type: 'string', group: 'cierre' }),
    richTextField({ name: 'closingText', title: 'Texto del cierre', group: 'cierre' }),
    defineField({
      name: 'closingCtaPrimaryHref',
      title: 'Destino del botón "Start application"',
      description: 'A dónde lleva el botón. Puede ser un ancla dentro de esta misma página (ej. "#apply") o una URL completa. Si lo dejas vacío, lleva a "#apply".',
      type: 'string',
      group: 'cierre',
    }),
  ],
  preview: {
    select: { title: 'heroHeading', media: 'heroImage' },
    prepare({ title, media }) {
      return { title: title || 'Página Volunteering', media }
    },
  },
})
