import { defineField, defineType } from 'sanity'

export const pageSobreNos = defineType({
  name: 'pageSobreNos',
  title: 'Página Sobre nós',
  type: 'document',
  groups: [
    { name: 'hero', title: 'Portada', default: true },
    { name: 'historia', title: 'Historia' },
    { name: 'valores', title: 'Valores' },
    { name: 'equipo', title: 'Equipo' },
    { name: 'voluntarios', title: 'Voluntarios históricos' },
    { name: 'iniciativas', title: 'Iniciativas' },
    { name: 'partners', title: 'Partners' },
    { name: 'cierre', title: 'Cierre' },
  ],
  fields: [
    defineField({
      name: 'heroEyebrow',
      title: 'Etiqueta pequeña',
      description: 'Por ejemplo: "Desde 2013 · Ferrol, Galicia".',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'heroHeading',
      title: 'Titular',
      description: 'El titular grande. Debe ser una frase completa que termine en punto.',
      type: 'string',
      group: 'hero',
      validation: (Rule) => Rule.required().error('Esta página necesita un titular.'),
    }),
    defineField({
      name: 'heroHeadingAccent',
      title: 'Fragmento destacado del titular',
      description:
        'La parte del titular que debe pintarse en el color de acento (debe aparecer tal cual dentro del titular).',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'heroText',
      title: 'Texto de la portada',
      type: 'text',
      rows: 3,
      group: 'hero',
    }),
    defineField({
      name: 'heroStats',
      title: 'Números destacados',
      type: 'array',
      of: [{ type: 'statItem' }],
      group: 'hero',
      validation: (Rule) => Rule.max(3).error('Como mucho tres números en el hero.'),
    }),
    defineField({
      name: 'historiaIntro',
      title: 'Introducción',
      type: 'sectionIntro',
      group: 'historia',
    }),
    defineField({
      name: 'historiaParagraphs',
      title: 'Párrafos de la historia',
      description: 'El origen de Xeración: por qué nació, qué problema resuelve.',
      type: 'array',
      of: [{ type: 'text', rows: 3 }],
      group: 'historia',
    }),
    defineField({
      name: 'timeline',
      title: 'Línea de tiempo',
      type: 'array',
      of: [{ type: 'timelineMilestone' }],
      group: 'historia',
    }),
    defineField({
      name: 'valoresIntro',
      title: 'Introducción',
      type: 'sectionIntro',
      group: 'valores',
    }),
    defineField({
      name: 'values',
      title: 'Valores',
      type: 'array',
      of: [{ type: 'valueItem' }],
      group: 'valores',
    }),
    defineField({
      name: 'equipoIntro',
      title: 'Introducción',
      type: 'sectionIntro',
      group: 'equipo',
    }),
    defineField({
      name: 'teamMembers',
      title: 'Equipo actual',
      type: 'array',
      of: [{ type: 'teamMember' }],
      group: 'equipo',
    }),
    defineField({
      name: 'volunteersNumber',
      title: 'Número grande',
      description: 'Por ejemplo: "60+".',
      type: 'string',
      group: 'voluntarios',
    }),
    defineField({
      name: 'volunteersSubtitle',
      title: 'Subtítulo',
      type: 'text',
      rows: 2,
      group: 'voluntarios',
    }),
    defineField({
      name: 'volunteersCtaLabel',
      title: 'Texto del botón',
      description: 'Por ejemplo: "¿Quieres ser el próximo? →".',
      type: 'string',
      group: 'voluntarios',
    }),
    defineField({
      name: 'volunteersCtaUrl',
      title: 'Enlace del botón',
      type: 'string',
      group: 'voluntarios',
      initialValue: '/irse/',
    }),
    defineField({
      name: 'iniciativasIntro',
      title: 'Introducción',
      type: 'sectionIntro',
      group: 'iniciativas',
    }),
    defineField({
      name: 'iniciativas',
      title: 'Iniciativas',
      type: 'array',
      of: [{ type: 'initiative' }],
      group: 'iniciativas',
    }),
    defineField({
      name: 'partnersIntro',
      title: 'Introducción',
      type: 'sectionIntro',
      group: 'partners',
    }),
    defineField({
      name: 'partners',
      title: 'Partners',
      description: 'Los nombres se muestran como logos de texto.',
      type: 'array',
      of: [{ type: 'string' }],
      group: 'partners',
    }),
    defineField({
      name: 'closingHeading',
      title: 'Título del cierre',
      type: 'string',
      group: 'cierre',
    }),
    defineField({
      name: 'closingText',
      title: 'Texto del cierre',
      type: 'text',
      rows: 2,
      group: 'cierre',
    }),
  ],
  preview: {
    select: { title: 'heroHeading' },
    prepare({ title }) {
      return { title: title || 'Página Sobre nós' }
    },
  },
})
