import type {
  Initiative,
  Partner,
  SectionIntro,
  StatItem,
  TeamMember,
  Testimonial,
  TimelineMilestone,
  ValueItem,
} from './types'

export const pageNosotrosEs = {
  heroEyebrow: 'Desde 2013 · Ferrol, Galicia',
  heroHeading: 'No somos una ONG más. Somos tu red en Europa.',
  heroHeadingAccent: 'tu red en Europa',
  heroText:
    'Somos jóvenes que ayudamos a otros jóvenes a vivir su aventura europea. Sin protocolo, sin papeleo interminable — con la experiencia de más de una década haciendo esto.',
  heroStats: [
    { value: '500+', label: 'jóvenes participantes' },
    { value: '13', label: 'años activos' },
    { value: '30+', label: 'países' },
  ] satisfies StatItem[],
  heroBackgroundImage: undefined as string | undefined,
  historiaIntro: { eyebrow: 'Nuestra historia', heading: 'De una idea en un bar a una red por toda Europa.' } satisfies SectionIntro,
  historiaParagraphs: [
    'Xeración nació en 2013 en Ferrol, cuando un grupo de amigos volvió de sus propios voluntariados europeos y se dio cuenta de que en la ciudad no había forma fácil de repetir la experiencia — ni de traer a nadie de fuera.',
    'El problema era simple: la información sobre programas europeos existía, pero estaba dispersa, en inglés técnico, y sin nadie cercano que acompañara el proceso paso a paso. Decidimos ser esa persona cercana.',
    'Trece años después seguimos con la misma idea: quitar de en medio el papeleo y la incertidumbre para que decir «me voy» sea lo más fácil de todo el viaje.',
  ],
  timeline: [
    { year: '2013', title: 'Fundación', description: 'Un grupo de amigos en Ferrol decide montar Xeración.' },
    { year: '2015', title: 'Primeros voluntarios europeos', description: 'Llegan a Ferrol los primeros jóvenes de fuera acogidos por la asociación.' },
    { year: '2021', title: 'Acreditación CES', description: 'Xeración se acredita como organización de acogida y envío del Cuerpo Europeo de Solidaridad.' },
    { year: '2024', title: '500+ participantes', description: 'Superamos los 500 jóvenes que han pasado por algún programa de Xeración.' },
    { year: '2025', title: 'Apertura Das Nest', description: 'Abrimos Das Nest, nuestro primer espacio de alojamiento propio para voluntariado.' },
  ] satisfies TimelineMilestone[],
  valoresIntro: { eyebrow: 'Cómo trabajamos', heading: 'Seis ideas que no negociamos.' } satisfies SectionIntro,
  values: [
    { icon: '✈️', title: 'Movilidad', description: 'Creemos que moverse por Europa debería estar al alcance de cualquier joven gallego, tenga o no dinero para pagárselo.' },
    { icon: '🤝', title: 'Cooperación', description: 'Trabajamos con organizaciones de toda Europa que comparten la misma manera de hacer las cosas: sin prisa, con seguimiento real.' },
    { icon: '🗳️', title: 'Democracia', description: 'Fomentamos que los jóvenes participen activamente en las decisiones que les afectan, dentro y fuera de la asociación.' },
    { icon: '🌍', title: 'Tolerancia', description: 'Cada intercambio y cada voluntariado es una excusa para desmontar prejuicios, empezando por los nuestros.' },
    { icon: '💚', title: 'Salud', description: 'Cuidamos el bienestar de quien se va y de quien llega — el acompañamiento no termina cuando sube al avión.' },
    { icon: '🌿', title: 'Ecología', description: 'Priorizamos el tren cuando es posible y elegimos proyectos que dejan huella positiva en el sitio que los acoge.' },
  ] satisfies ValueItem[],
  equipoIntro: { eyebrow: 'Quién está detrás', heading: 'El equipo ahora mismo.' } satisfies SectionIntro,
  teamMembers: [
    { name: 'Fran Sequeiro', role: 'Coordinación', linkUrl: 'https://linkedin.com/in/fransequeiro' },
    { name: 'Amélie Arles', role: 'Voluntaria · Francia' },
    { name: 'Caitlin Wessels', role: 'Voluntaria · Países Bajos' },
    { name: 'Marie Salaün', role: 'Voluntaria · Francia' },
  ] satisfies TeamMember[],
  volunteersNumber: '60+',
  volunteersSubtitle: 'voluntarios europeos de más de 20 países han pasado por Xeración desde 2013.',
  volunteersCtaLabel: 'Quiero ser el próximo →',
  volunteersCtaUrl: '/experiencias/',
  pastVolunteersIntro: undefined as SectionIntro | undefined,
  pastVolunteers: [] as TeamMember[],
  iniciativasIntro: { eyebrow: 'Más allá del voluntariado', heading: 'Tres proyectos propios.' } satisfies SectionIntro,
  iniciativas: [
    { icon: '🏡', name: 'Das Nest', description: 'Nuestro espacio de alojamiento para voluntariado en Ferrol, pensado y gestionado por quienes ya pasaron por aquí.', colorScheme: 'blue' },
    { icon: '🌿', name: 'Building Nature', description: 'Proyectos de voluntariado ambiental en la ría de Ferrol: limpiezas de costa, reforestación, sensibilización.', colorScheme: 'green' },
    { icon: '🎤', name: 'Speak Factor', description: 'Talleres y clubs de idiomas abiertos a toda la comarca, llevados por nuestros propios voluntarios internacionales.', colorScheme: 'orange' },
  ] satisfies Initiative[],
  partnersIntro: { eyebrow: 'Con quién trabajamos' } satisfies SectionIntro,
  partners: [
    { name: 'ERASMUS+' },
    { name: 'Cuerpo Europeo de Solidaridad' },
    { name: 'Eurodesk' },
    { name: 'Xunta de Galicia' },
    { name: 'Concello de Ferrol' },
    { name: 'Google for Nonprofits' },
  ] satisfies Partner[],
  legalName: 'Asociación Xeración',
  legalCif: 'G70385091',
  legalAddress: 'Rúa Almendra 9, 15402 Ferrol',
  legalOid: 'E10060426',
  legalPic: '948920640',
  memoriaAnualUrl: undefined as string | undefined,
  accreditations: [
    { name: 'Acreditación Erasmus+ (envío, acogida y coordinación)' },
    { name: 'Acreditación Cuerpo Europeo de Solidaridad' },
  ] satisfies Partner[],
  closingHeading: '¿Listo para vivir tu aventura europea?',
  closingText: 'Todas nuestras oportunidades están financiadas. El único requisito es querer.',
  closingCtaPrimaryHref: undefined as string | undefined,
}

export const nosotrosTestimonialsEs: Testimonial[] = [
  { quote: 'Vine a Ferrol sin conocer a nadie. Salí con una segunda familia repartida por media Europa.', name: 'Tasos Batzonis', originCity: 'Grecia', program: 'ESC' },
  { quote: 'Pensé que sería solo un año raro en mi carrera. Fue el año que más aprendí de mí misma.', name: 'Martina Aramini', originCity: 'Italia', program: 'ESC' },
  { quote: 'Nadie me avisó de que echaría tanto de menos la lluvia de Ferrol al volver a casa.', name: 'Linda Pūdāne', originCity: 'Letonia', program: 'ESC' },
]
